### ISSUE TITLE
Llistat d'objectes a la botiga

### ISSUE THREAD

**Issue by Reda3334** [Reda3334/ProyectoDSA-Backend#3]

**Comment by Reda3334** [comment]
las principals tascas que hauras de fer seran: desenvolupar una ruta de la api rest que proporcioni la llista d'objectes 
desenvolupar una pantalleta amb html que utilitzi un codi de javascript(jQuery) que aqtqauin a la ruta de backend previamente indicada

**Comment by janvinas** [comment]
ufff molta feina
